name: PhantomSMP
version: @version@
author: SimonOrJ
description: Advanced phantom mechanics especially for SMP servers
main: com.simonorj.mc.phantomsmp.PhantomSMP
website: https://github.com/SimonOrJ/PhantomSMP
api-version: 1.13
